mongo:
  container_name: pinakarri_db
  image: mongo
  volumes:
  - /data/pinakarri/db:/data/db

  restart: always

pinakarri-app:
  container_name: pinakarri_app
  build: app

  ports:
  - 9000:8080

  links:
   - mongo:db

  restart: always

pinakarri-app-read-only:
  container_name: pinakarri_app_read_only
  build: app

  ports:
  - 9002:8080

  links:
   - mongo:db

  restart: always

  environment:
    - READ_ONLY=1


mongo-express:
  container_name: pinakarri_admin
  image: knickers/mongo-express:0.30.11

  ports:
    - 9001:8081
  links:
    - mongo
  
  restart: always


