pinakarri-db:
  image: mongo:3
  container_name: pinakarri-db
  volumes:
    - /data/pinkarri/db:/data/db
    
pinkarri-app:
  build: app
  container_name: pinakarri-app
  ports:
    - 8080:8080
  links:
    - pinakarri-db:db

  volumes:
    - /vagrant/app/node/server.js:/usr/src/app/server.js
